version: '3.8'

# linux amd64로 플랫폼을 정했기 때문에 ECS task 생성할 때 linux/X86_64로 운영체제/아키텍처를 정해주어야 됨 안 그러면 에러남

services:
  auth-api:
    platform: linux/amd64
    container_name: monorepo-auth-api
    build:
      context: .
      dockerfile: ./apps/auth-api/Dockerfile
    image: auth-api:latest
    ports:
      - '3300:3300'
    volumes:
      - .:/src:cached
  cats-api:
    platform: linux/amd64
    container_name: monorepo-cats-api
    build:
      context: .
      dockerfile: ./apps/cats/Dockerfile
    image: cats-api:latest
    ports:
      - '3000:3000'
    volumes:
      - .:/src:cached
