name: Build and Push Docker Images

on:
  push:
    branches:
      - main
    paths:
      - 'apps/auth-api/**'
      - 'apps/cats/**'
  pull_request:
    branches:
      - main  # PR이 main 브랜치로 병합될 때 실행합니다.
    paths:
      - 'apps/auth-api/**'
      - 'apps/cats/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

      - name: Build and Push Auth API
        if: contains(github.event.head_commit.message, '[auth-api]')
        run: |
          docker-compose build auth-api
          docker tag monorepo-auth-api:latest choijewon/dockerizing-nestjs-monorepo-auth-api:latest
          docker push choijewon/dockerizing-nestjs-monorepo-auth-api:latest

      - name: Build and Push Cat API
        if: contains(github.event.head_commit.message, '[cat-api]')
        run: |
          docker-compose build cats-api
          docker tag monorepo-cats-api:latest choijewon/dockerizing-nestjs-monorepo-cats-api:latest
          docker push choijewon/dockerizing-nestjs-monorepo-cats-api:latest

      - name: Build and Push All
        if: contains(github.event.head_commit.message, '[All]')
        run: |
          docker-compose build
          docker tag monorepo-auth-api:latest choijewon/dockerizing-nestjs-monorepo-auth-api:latest
          docker push choijewon/dockerizing-nestjs-monorepo-auth-api:latest
          docker tag monorepo-cats-api
